{% set version = "0.3.7" %}
{% set name = "sharedmem" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://pypi.python.org/packages/source/s/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 483e414b8c5d03093a02baf548449f1d8426a88855556fa42102bba82b86b2a8

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy

test:
  imports:
    - sharedmem

about:
  home: http://github.com/rainwoodman/sharedmem
  license: GPL-3.0
  license_family: GPL
  summary: 'Dispatch your trivially parallizable jobs with sharedmem. '
