package:
  name: justbackoff
  version: "0.5.0"

source:
  url: https://files.pythonhosted.org/packages/cf/7c/f0a2d0e6b6e0908c2c722253dae6c5f1cb78df8fa227ad9021a14402de8c/justbackoff-0.5.0.tar.gz
  sha256: 57c8d7419975eef8a216c2d48892e09f8e0fcef6d58e62effd770ee6da762071

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - justbackoff

about:
  home: https://github.com/admiralobvious/justbackoff
  license: MIT
  summary: 'Simple backoff algorithm in Python'
  license_family: MIT
