package:
  name: zeroc-ice
  version: '3.7.3'

source:
  url: https://files.pythonhosted.org/packages/e1/22/9bf3c799244be9baaeb34a3de0573c8a468ad29f9ac859861ffa0c7c68e1/zeroc-ice-3.7.3.tar.gz
  sha256: 1adec3b54c77c46acfc8a99d6336ce9a0223a7016852666358133cbe37d99744

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - bzip2

  run:
    - python
    - bzip2

test:
  imports:
    - Ice

about:
  home: https://github.com/zeroc-ice
  license: GPL v2 with exceptions
  summary: Ice is a comprehensive RPC framework that helps you network your software with minimal effort.
