package:
  name: pronto
  version: "1.0.0"

source:
  url: https://files.pythonhosted.org/packages/f8/1c/54ab850781370ba6841b83c3fca3e0d14e105315f5f3e8f5183e467f4d4a/pronto-1.0.0.zip
  sha256: 519a9beef96246cfce346c0be289631d999c43a2f4b797de0e872a9ee1ede543
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  number: 0
  entry_points:
    - pronto = pronto:main

requirements:
  host:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - pronto
    - pronto.parser

about:
  home: http://github.com/althonos/pronto
  license: MIT License
  summary: 'Python frontend to ontologies'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
